steps:
  # install dependencies
  - name: python:3.11
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  
  - name: python:3.11
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  # run in python 3.11 which is latest version in Cloud Composer
  - name: python:3.11
    entrypoint: python3.8
    args: ["-m", "pytest", "-s", "dags/"]

options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'